#!/usr/bin/env node
// Self-hosts the on-canvas annotation / caption faces.
//
// index.css used to open with an `@import` of fonts.googleapis.com covering the families
// `CaptionsPane` offers. That is a network fetch on every cold start of a desktop
// recorder, and when it fails the failure is silent and lands in the OUTPUT: the picker
// falls back to a system face and the compositor burns that face into the video. Offline is
// not an edge case for this app -- styles/fonts.css already self-hosts the Geist UI pair for
// precisely this reason, and named this set as the gap it had not closed.
//
// Downloads the woff2 for each family below into `src/assets/fonts/annotation/<slug>/` and
// writes `src/styles/annotation-fonts.css` with the matching `@font-face` rules. The set is
// ~582 KB because only the latin, latin-ext and vietnamese subsets are kept -- they cover the
// en / vi locales, and CJK annotations fall through to the system stacks. Inter is
// published under the SIL Open Font License 1.1, which is what makes redistributing it
// inside the app legal; see the generated LICENSES.txt next to the files, and
// THIRD-PARTY-NOTICES.md.
//
// The output is COMMITTED. This script exists to regenerate it, not to run at build time --
// a build that reaches for the network to produce identical bytes is a build that can fail
// for reasons unrelated to the code.
//
// Usage: node scripts/fetch-fonts.mjs   (needs network)

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const FONTS_DIR = path.join(ROOT, "src", "assets", "fonts", "annotation");
const CSS_OUT = path.join(ROOT, "src", "styles", "annotation-fonts.css");
const LICENSE_OUT = path.join(FONTS_DIR, "LICENSES.txt");

/** Google Fonts `family=` specs, one per family. Keep in step with `CAPTION_FONTS` in
 *  `src/components/ai-edition/CaptionsPane.tsx`: a face offered there and missing here is
 *  a face that renders as a fallback, which is the bug this script exists to prevent.
 *
 *  Inter is the only one left. The picker's other family, Geist, is self-hosted by
 *  styles/fonts.css and is not a Google Font, so it is not this script's to fetch.
 *  Fifteen display/serif/mono families were dropped -- nothing shipped as a default
 *  used them and they cost ~3 MB of committed woff2. Re-adding a name here brings its
 *  weight back, so add it to CAPTION_FONTS in the same change or not at all. */
const FAMILIES = ["Inter:ital,wght@0,400;0,700;1,400;1,700"];

const SUBSETS = new Set(["latin", "latin-ext", "vietnamese"]);

/** A modern Chrome UA makes the CSS API return woff2 with unicode-range subsets. Ask as
 *  anything older and it serves one fat ttf per family and the set stops being ~143 KB. */
const USER_AGENT =
	"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

function slugify(family) {
	return family
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/(^-|-$)/g, "");
}

async function fetchText(url) {
	const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
	if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
	return res.text();
}

async function fetchBinary(url) {
	const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
	if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
	return Buffer.from(await res.arrayBuffer());
}

/** Split a Google Fonts stylesheet into `{ subset, block }` @font-face entries. The subset
 *  name is never a declaration -- it arrives only as a CSS comment above each block, which
 *  is why this parses by regex rather than asking a CSS parser for the rule. */
function parseFontFaces(css) {
	const entries = [];
	const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
	for (const match of css.matchAll(re)) {
		entries.push({ subset: match[1], block: match[2] });
	}
	return entries;
}

function readDeclaration(block, name) {
	const match = block.match(new RegExp(`${name}\\s*:\\s*([^;]+);`));
	return match ? match[1].trim() : null;
}

async function main() {
	fs.rmSync(FONTS_DIR, { recursive: true, force: true });
	fs.mkdirSync(FONTS_DIR, { recursive: true });

	const cssParts = [
		"/* The on-canvas annotation / caption face, self-hosted.",
		" *",
		" * Generated by scripts/fetch-fonts.mjs -- do not edit by hand. This replaces the",
		" * Google Fonts @import that used to sit at the top of index.css: it fetched the",
		" * caption families from fonts.googleapis.com on every cold start, so on a plane",
		" * the caption picker silently fell back to a system face and the export burned in",
		" * the wrong type. src/styles/fonts.css already self-hosts the Geist UI pair for",
		" * exactly this reason and called this set out as the remaining gap.",
		" *",
		" * Inter only. The picker offers two families -- Inter from here, Geist from",
		" * styles/fonts.css -- and fifteen further display/serif/mono faces were dropped",
		" * because nothing shipped as a default used them and they cost ~3 MB of committed",
		" * woff2. Latin, latin-ext and vietnamese subsets only, keyed by unicode-range, so",
		" * what is left costs ~582 KB. SIL Open Font License 1.1 -- see",
		" * src/assets/fonts/annotation/LICENSES.txt and THIRD-PARTY-NOTICES.md.",
		" *",
		" * The faces live under src/assets/, NOT public/, and the urls here are relative so",
		" * that Vite resolves and fingerprints them. A packaged build loads the renderer with",
		" * `win.loadFile(...)` -- i.e. over file:// -- where an absolute `/fonts/...` url",
		" * resolves against the filesystem root and 404s, so every face would silently fall",
		" * back in exactly the offline build this bundling exists to fix. styles/fonts.css",
		" * loads Geist the same relative way. */",
		"",
	];
	const licenseLines = [
		"Fonts in this directory were downloaded from Google Fonts by scripts/fetch-fonts.mjs.",
		"All of them are licensed under the SIL Open Font License, Version 1.1",
		"(https://openfontlicense.org/). The OFL requires the licence text and copyright",
		"notice to travel WITH the font files, not merely to be linked, so each family's",
		"own OFL.txt is committed beside its woff2 in the directory named below.",
		"",
	];
	let totalBytes = 0;

	for (const spec of FAMILIES) {
		const family = spec.split(":")[0];
		const slug = slugify(family);
		// The spec's own `:;,@` are syntax to the CSS API, so they survive encoding.
		const query = encodeURIComponent(spec)
			.replace(/%3A/g, ":")
			.replace(/%3B/g, ";")
			.replace(/%2C/g, ",")
			.replace(/%40/g, "@");
		const css = await fetchText(`https://fonts.googleapis.com/css2?family=${query}&display=swap`);
		const faces = parseFontFaces(css).filter((face) => SUBSETS.has(face.subset));
		if (faces.length === 0) throw new Error(`No usable @font-face blocks for ${family}`);

		const familyDir = path.join(FONTS_DIR, slug);
		fs.mkdirSync(familyDir, { recursive: true });
		// The OFL obliges us to redistribute the licence and copyright notice with the
		// binaries. google/fonts keeps them under a squashed slug (`ofl/plusjakartasans`),
		// which is NOT our hyphenated directory slug. A 404 throws, and that is deliberate:
		// shipping a face whose licence we could not fetch is the failure worth stopping for.
		const oflSlug = family.toLowerCase().replace(/[^a-z0-9]/g, "");
		const ofl = await fetchText(
			`https://raw.githubusercontent.com/google/fonts/main/ofl/${oflSlug}/OFL.txt`,
		);
		fs.writeFileSync(path.join(familyDir, "OFL.txt"), ofl);
		cssParts.push(`/* ${family} */`);

		for (const face of faces) {
			const src = readDeclaration(face.block, "src");
			const fileUrl = src?.match(/url\(([^)]+)\)/)?.[1];
			if (!fileUrl) throw new Error(`No src url in ${family} ${face.subset}`);
			const style = readDeclaration(face.block, "font-style") ?? "normal";
			const weight = readDeclaration(face.block, "font-weight") ?? "400";
			const unicodeRange = readDeclaration(face.block, "unicode-range");
			const fileName = `${slug}-${face.subset}-${weight}-${style}.woff2`;
			const data = await fetchBinary(fileUrl);
			fs.writeFileSync(path.join(familyDir, fileName), data);
			totalBytes += data.length;

			cssParts.push(
				"@font-face {",
				`  font-family: "${family}";`,
				`  font-style: ${style};`,
				`  font-weight: ${weight};`,
				"  font-display: swap;",
				`  src: url("../assets/fonts/annotation/${slug}/${fileName}") format("woff2");`,
				...(unicodeRange ? [`  unicode-range: ${unicodeRange};`] : []),
				"}",
			);
		}
		cssParts.push("");
		licenseLines.push(`- ${family} -- src/assets/fonts/annotation/${slug}/OFL.txt`);
		console.log(`${family}: ${faces.length} files`);
	}

	fs.writeFileSync(CSS_OUT, `${cssParts.join("\n").trimEnd()}\n`);
	fs.writeFileSync(LICENSE_OUT, `${licenseLines.join("\n")}\n`);
	console.log(`Wrote ${CSS_OUT} (${(totalBytes / 1024).toFixed(0)} KB of woff2)`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
