#!/usr/bin/env node
// Self-hosts the on-canvas annotation / caption faces.
//
// index.css used to open with an `@import` of fonts.googleapis.com covering the sixteen
// families `CaptionsPane` offers. That is a network fetch on every cold start of a desktop
// recorder, and when it fails the failure is silent and lands in the OUTPUT: the picker
// falls back to a system face and the compositor burns that face into the video. Offline is
// not an edge case for this app -- styles/fonts.css already self-hosts the Geist UI pair for
// precisely this reason, and named this set as the gap it had not closed.
//
// Downloads the woff2 for each family below into `public/fonts/<slug>/` and writes
// `src/styles/annotation-fonts.css` with the matching `@font-face` rules. The whole set is
// ~143 KB because only the latin, latin-ext and vietnamese subsets are kept -- they cover the
// en / vi locales, and CJK annotations fall through to the system stacks. All sixteen are
// published under the SIL Open Font License 1.1, which is what makes redistributing them
// inside the app legal; see public/fonts/LICENSES.txt and THIRD-PARTY-NOTICES.md.
//
// The output is COMMITTED. This script exists to regenerate it, not to run at build time --
// a build that reaches for the network to produce identical bytes is a build that can fail
// for reasons unrelated to the code.
//
// Usage: node scripts/fetch-fonts.mjs   (needs network)

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const FONTS_DIR = path.join(ROOT, "public", "fonts");
const CSS_OUT = path.join(ROOT, "src", "styles", "annotation-fonts.css");
const LICENSE_OUT = path.join(FONTS_DIR, "LICENSES.txt");

/** Google Fonts `family=` specs, one per family. Keep in step with `CAPTION_FONTS` in
 *  `src/components/ai-edition/CaptionsPane.tsx`: a face offered there and missing here is
 *  a face that renders as a fallback, which is the bug this script exists to prevent. */
const FAMILIES = [
	"Inter:ital,wght@0,400;0,700;1,400;1,700",
	"Plus Jakarta Sans:ital,wght@0,400;0,700;1,400;1,700",
	"Space Grotesk:wght@400;700",
	"DM Sans:ital,wght@0,400;0,700;1,400;1,700",
	"Sora:wght@400;700",
	"Manrope:wght@400;700",
	"IBM Plex Sans:ital,wght@0,400;0,700;1,400;1,700",
	"Playfair Display:ital,wght@0,400;0,700;1,400;1,700",
	"Merriweather:ital,wght@0,400;0,700;1,400;1,700",
	"Lora:ital,wght@0,400;0,700;1,400;1,700",
	"IBM Plex Mono:ital,wght@0,400;0,700;1,400;1,700",
	"Fira Code:wght@400;700",
	"Bebas Neue",
	"Oswald:wght@400;700",
	"Caveat:wght@400;700",
	"Permanent Marker",
];

const SUBSETS = new Set(["latin", "latin-ext", "vietnamese"]);

/** A modern Chrome UA makes the CSS API return woff2 with unicode-range subsets. Ask as
 *  anything older and it serves one fat ttf per family and the set stops being ~143 KB. */
const USER_AGENT =
	"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

function slugify(family) {
	return family
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/(^-|-$)/g, "");
}

async function fetchText(url) {
	const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
	if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
	return res.text();
}

async function fetchBinary(url) {
	const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
	if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
	return Buffer.from(await res.arrayBuffer());
}

/** Split a Google Fonts stylesheet into `{ subset, block }` @font-face entries. The subset
 *  name is never a declaration -- it arrives only as a CSS comment above each block, which
 *  is why this parses by regex rather than asking a CSS parser for the rule. */
function parseFontFaces(css) {
	const entries = [];
	const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
	for (const match of css.matchAll(re)) {
		entries.push({ subset: match[1], block: match[2] });
	}
	return entries;
}

function readDeclaration(block, name) {
	const match = block.match(new RegExp(`${name}\\s*:\\s*([^;]+);`));
	return match ? match[1].trim() : null;
}

async function main() {
	fs.rmSync(FONTS_DIR, { recursive: true, force: true });
	fs.mkdirSync(FONTS_DIR, { recursive: true });

	const cssParts = [
		"/* The on-canvas annotation / caption faces, self-hosted.",
		" *",
		" * Generated by scripts/fetch-fonts.mjs -- do not edit by hand. These replace the",
		" * Google Fonts @import that used to sit at the top of index.css: it fetched these",
		" * same sixteen families from fonts.googleapis.com on every cold start, so on a",
		" * plane the caption picker silently fell back to a system face and the export",
		" * burned in the wrong type. src/styles/fonts.css already self-hosts the Geist UI",
		" * pair for exactly this reason and called this set out as the remaining gap.",
		" *",
		" * Latin, latin-ext and vietnamese subsets only, keyed by unicode-range, which is",
		" * why the whole set costs ~143 KB. SIL Open Font License 1.1 -- see",
		" * public/fonts/LICENSES.txt and THIRD-PARTY-NOTICES.md. */",
		"",
	];
	const licenseLines = [
		"Fonts in this directory were downloaded from Google Fonts by scripts/fetch-fonts.mjs.",
		"All of them are licensed under the SIL Open Font License, Version 1.1",
		"(https://openfontlicense.org/). Each family's own OFL text and copyright",
		"notice is available from its Google Fonts page (https://fonts.google.com/).",
		"",
	];
	let totalBytes = 0;

	for (const spec of FAMILIES) {
		const family = spec.split(":")[0];
		const slug = slugify(family);
		// The spec's own `:;,@` are syntax to the CSS API, so they survive encoding.
		const query = encodeURIComponent(spec)
			.replace(/%3A/g, ":")
			.replace(/%3B/g, ";")
			.replace(/%2C/g, ",")
			.replace(/%40/g, "@");
		const css = await fetchText(`https://fonts.googleapis.com/css2?family=${query}&display=swap`);
		const faces = parseFontFaces(css).filter((face) => SUBSETS.has(face.subset));
		if (faces.length === 0) throw new Error(`No usable @font-face blocks for ${family}`);

		const familyDir = path.join(FONTS_DIR, slug);
		fs.mkdirSync(familyDir, { recursive: true });
		cssParts.push(`/* ${family} */`);

		for (const face of faces) {
			const src = readDeclaration(face.block, "src");
			const fileUrl = src?.match(/url\(([^)]+)\)/)?.[1];
			if (!fileUrl) throw new Error(`No src url in ${family} ${face.subset}`);
			const style = readDeclaration(face.block, "font-style") ?? "normal";
			const weight = readDeclaration(face.block, "font-weight") ?? "400";
			const unicodeRange = readDeclaration(face.block, "unicode-range");
			const fileName = `${slug}-${face.subset}-${weight}-${style}.woff2`;
			const data = await fetchBinary(fileUrl);
			fs.writeFileSync(path.join(familyDir, fileName), data);
			totalBytes += data.length;

			cssParts.push(
				"@font-face {",
				`  font-family: "${family}";`,
				`  font-style: ${style};`,
				`  font-weight: ${weight};`,
				"  font-display: swap;",
				`  src: url("/fonts/${slug}/${fileName}") format("woff2");`,
				...(unicodeRange ? [`  unicode-range: ${unicodeRange};`] : []),
				"}",
			);
		}
		cssParts.push("");
		licenseLines.push(`- ${family} (public/fonts/${slug}/)`);
		console.log(`${family}: ${faces.length} files`);
	}

	fs.writeFileSync(CSS_OUT, `${cssParts.join("\n").trimEnd()}\n`);
	fs.writeFileSync(LICENSE_OUT, `${licenseLines.join("\n")}\n`);
	console.log(`Wrote ${CSS_OUT} (${(totalBytes / 1024).toFixed(0)} KB of woff2)`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
