#!/usr/bin/env node
/**
 * Self-host the annotation fonts.
 *
 * Downloads the woff2 files for the families listed below from Google Fonts
 * (all are published under the SIL Open Font License 1.1) into
 * `public/fonts/<family-slug>/` and writes `src/fonts.css` with the matching
 * `@font-face` rules, so the app never fetches fonts at runtime (the editor
 * runs offline and the exporter draws text on a canvas, where an unloaded
 * web font silently falls back).
 *
 * Only the latin, latin-ext and vietnamese subsets are kept: they cover the
 * en / vi locales; CJK annotations use the system font stacks.
 *
 * Usage: node scripts/fetch-fonts.mjs   (needs network; the result is committed)
 */
import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const FONTS_DIR = path.join(ROOT, 'public', 'fonts')
const CSS_OUT = path.join(ROOT, 'src', 'fonts.css')
const LICENSE_OUT = path.join(FONTS_DIR, 'LICENSES.txt')

/** Google Fonts `family=` specs, one per family. */
const FAMILIES = [
  'Inter:ital,wght@0,400;0,700;1,400;1,700',
  'Plus Jakarta Sans:ital,wght@0,400;0,700;1,400;1,700',
  'Space Grotesk:wght@400;700',
  'DM Sans:ital,wght@0,400;0,700;1,400;1,700',
  'Sora:wght@400;700',
  'Manrope:wght@400;700',
  'IBM Plex Sans:ital,wght@0,400;0,700;1,400;1,700',
  'Playfair Display:ital,wght@0,400;0,700;1,400;1,700',
  'Merriweather:ital,wght@0,400;0,700;1,400;1,700',
  'Lora:ital,wght@0,400;0,700;1,400;1,700',
  'IBM Plex Mono:ital,wght@0,400;0,700;1,400;1,700',
  'Fira Code:wght@400;700',
  'Bebas Neue',
  'Oswald:wght@400;700',
  'Caveat:wght@400;700',
  'Permanent Marker',
]

const SUBSETS = new Set(['latin', 'latin-ext', 'vietnamese'])

// A modern Chrome UA makes the CSS API return woff2 with unicode-range subsets.
const USER_AGENT =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

function slugify(family) {
  return family
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT } })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return res.text()
}

async function fetchBinary(url) {
  const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT } })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return Buffer.from(await res.arrayBuffer())
}

/** Split a Google Fonts stylesheet into `{ subset, block }` @font-face entries. */
function parseFontFaces(css) {
  const entries = []
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g
  for (const match of css.matchAll(re)) {
    entries.push({ subset: match[1], block: match[2] })
  }
  return entries
}

function readDeclaration(block, name) {
  const match = block.match(new RegExp(`${name}\\s*:\\s*([^;]+);`))
  return match ? match[1].trim() : null
}

async function main() {
  fs.rmSync(FONTS_DIR, { recursive: true, force: true })
  fs.mkdirSync(FONTS_DIR, { recursive: true })

  const cssParts = [
    '/* Generated by scripts/fetch-fonts.mjs - do not edit by hand. */',
    '/* Fonts are self-hosted under public/fonts (SIL Open Font License 1.1, see public/fonts/LICENSES.txt). */',
    '',
  ]
  const licenseLines = [
    'Fonts in this directory were downloaded from Google Fonts by scripts/fetch-fonts.mjs.',
    'All of them are licensed under the SIL Open Font License, Version 1.1',
    "(https://openfontlicense.org/). Each family's own OFL text and copyright",
    'notice is available from its Google Fonts page (https://fonts.google.com/).',
    '',
  ]
  let totalBytes = 0

  for (const spec of FAMILIES) {
    const family = spec.split(':')[0]
    const slug = slugify(family)
    const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(spec).replace(/%3A/g, ':').replace(/%3B/g, ';').replace(/%2C/g, ',').replace(/%40/g, '@')}&display=swap`
    const css = await fetchText(url)
    const faces = parseFontFaces(css).filter((f) => SUBSETS.has(f.subset))
    if (faces.length === 0) throw new Error(`No usable @font-face blocks for ${family}`)

    const familyDir = path.join(FONTS_DIR, slug)
    fs.mkdirSync(familyDir, { recursive: true })
    cssParts.push(`/* ${family} */`)

    for (const face of faces) {
      const src = readDeclaration(face.block, 'src')
      const fileUrl = src?.match(/url\(([^)]+)\)/)?.[1]
      if (!fileUrl) throw new Error(`No src url in ${family} ${face.subset}`)
      const style = readDeclaration(face.block, 'font-style') ?? 'normal'
      const weight = readDeclaration(face.block, 'font-weight') ?? '400'
      const unicodeRange = readDeclaration(face.block, 'unicode-range')
      const fileName = `${slug}-${face.subset}-${weight}-${style}.woff2`
      const data = await fetchBinary(fileUrl)
      fs.writeFileSync(path.join(familyDir, fileName), data)
      totalBytes += data.length

      cssParts.push(
        '@font-face {',
        `  font-family: "${family}";`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url("/fonts/${slug}/${fileName}") format("woff2");`,
        ...(unicodeRange ? [`  unicode-range: ${unicodeRange};`] : []),
        '}',
      )
    }
    cssParts.push('')
    licenseLines.push(`- ${family} (public/fonts/${slug}/)`)
    console.log(`${family}: ${faces.length} files`)
  }

  fs.writeFileSync(CSS_OUT, `${cssParts.join('\n').trimEnd()}\n`)
  fs.writeFileSync(LICENSE_OUT, `${licenseLines.join('\n')}\n`)
  console.log(`Wrote ${CSS_OUT} (${(totalBytes / 1024 / 1024).toFixed(2)} MB of woff2)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
